/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewClasses;

import ControllerClasses.TaskListController;
import ModelClasses.Task;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kavindu
 */
public final class MainInterface extends javax.swing.JFrame {

    TaskListController tskListCtrl = new TaskListController();
    int tempId;
    
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        
        tskListCtrl.checkFile();    //check file  availability. if not then create new one.

        //get last higher id from data. because we need to maintain uniq id for task
        tskListCtrl.getAllTaskListFromFile();   //load all tasks from file
        tskListCtrl.getTskList().sortById();    //sort loaded task by ID
        tempId = tskListCtrl.getTskList().getLastTaskId();  //get last task ID and store it
        System.out.println("Last id entered : " + tempId);

        tskListCtrl.getAllTaskListFromFile();   //again load all the data to taskList
        allTaskBtn.setSelected(true);       //select all task button when loading
        loadtable();    //display that list in the table
        showTime();
        showDate();
        displaySummary();
       
     
    }
    
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss a");
                String time = s.format(d);
                timeDisplay.setText(time);
            }
        }).start();
    }
    
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy MMMM dd");
        String date = s.format(d);
        dateDisplay.setText(date);
    }
    
    public void loadtable(){  
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
        dft.setRowCount(0);
        
        Task current = tskListCtrl.getTskList().head;
        
        while (current != null) {            
            String status;
            if(current.isIsCompleted()){
                status = "Completed";
            }else{
                status = "Not Completed";
            }
            
            dft.addRow(new Object[]{current.getId() , current.getTitle() , current.getDescription() , current.getDueDate() , status});
            
            current = current.next;
        }
    }
    
    public void displaySummary(){
        
        Task current;
        
        //count no of  complete tasks
        tskListCtrl.setTskList(tskListCtrl.getTskList().getCompletedTaskList());
        int noOfCompleteTasks = 0;
        current = tskListCtrl.getTskList().head;
        while (current != null) {            
            noOfCompleteTasks++;
            current = current.next;
        }

        //get number of all tasks
        tskListCtrl.getAllTaskListFromFile();
        int noOfAllTasks = 0;
        current = tskListCtrl.getTskList().head;
        while (current != null) {            
            noOfAllTasks++;
            current = current.next;
        }
        
        
        int remainingTasks = noOfAllTasks - noOfCompleteTasks;
        int completePercentage = (noOfCompleteTasks*100)/noOfAllTasks;
        
        //display values
        noOfAllTasksLabel.setText(String.valueOf(noOfAllTasks));
        noOfRemainTasksLable.setText(String.valueOf(remainingTasks));
        noOfCompleteTasksLabel.setText(String.valueOf(noOfCompleteTasks));
        circleProgressBar1.setValue(completePercentage);  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showBtnGrp = new javax.swing.ButtonGroup();
        sortBtnGrp = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateDisplay = new javax.swing.JLabel();
        timeDisplay = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        noOfCompleteTasksLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        noOfAllTasksLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        noOfRemainTasksLable = new javax.swing.JLabel();
        circleProgressBar1 = new swing.CircleProgressBar();
        taskShowPannel = new javax.swing.JPanel();
        allTaskBtn = new javax.swing.JRadioButton();
        completedTaskBtn = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        sortByIdBtn = new javax.swing.JRadioButton();
        sortByDueDateBtn = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        completeCheckBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        dueDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Title              :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, 35));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Description  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 110, 28));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Due date      :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 110, 30));

        titleTxt.setBackground(new java.awt.Color(0, 0, 0));
        titleTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(255, 255, 255));
        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });
        jPanel1.add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 270, 35));

        descriptionTxt.setBackground(new java.awt.Color(0, 0, 0));
        descriptionTxt.setColumns(20);
        descriptionTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTxt.setForeground(new java.awt.Color(255, 255, 255));
        descriptionTxt.setRows(5);
        jScrollPane1.setViewportView(descriptionTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 270, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TASK MANAGER");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1210, 74));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TIME");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 60, 30));

        dateDisplay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jPanel3.add(dateDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 30));

        timeDisplay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jPanel3.add(timeDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/date and time banner.PNG"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 520, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/date and time banner.PNG"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 440, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 780, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 0, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Completed Tasks");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 26));

        noOfCompleteTasksLabel.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        noOfCompleteTasksLabel.setForeground(new java.awt.Color(255, 255, 255));
        noOfCompleteTasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfCompleteTasksLabel.setText("5");
        jPanel4.add(noOfCompleteTasksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 40, 26));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("All Tasks");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 49, 100, 26));

        noOfAllTasksLabel.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        noOfAllTasksLabel.setForeground(new java.awt.Color(255, 255, 255));
        noOfAllTasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfAllTasksLabel.setText("25");
        jPanel4.add(noOfAllTasksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 81, 40, 26));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Remaining Tasks");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 49, -1, 26));

        noOfRemainTasksLable.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        noOfRemainTasksLable.setForeground(new java.awt.Color(255, 255, 255));
        noOfRemainTasksLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfRemainTasksLable.setText("20");
        jPanel4.add(noOfRemainTasksLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 50));

        circleProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        circleProgressBar1.setForeground(new java.awt.Color(255, 255, 255));
        circleProgressBar1.setValue(40);
        circleProgressBar1.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        jPanel4.add(circleProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 137, 120, 100));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 319, 260));

        taskShowPannel.setBackground(new java.awt.Color(51, 0, 255));
        taskShowPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        taskShowPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showBtnGrp.add(allTaskBtn);
        allTaskBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        allTaskBtn.setForeground(new java.awt.Color(255, 255, 255));
        allTaskBtn.setText("All Tasks");
        allTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTaskBtnActionPerformed(evt);
            }
        });
        taskShowPannel.add(allTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 38, 98, -1));

        showBtnGrp.add(completedTaskBtn);
        completedTaskBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        completedTaskBtn.setForeground(new java.awt.Color(255, 255, 255));
        completedTaskBtn.setText("Completed Tasks");
        completedTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedTaskBtnActionPerformed(evt);
            }
        });
        taskShowPannel.add(completedTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 67, 132, -1));

        jPanel5.add(taskShowPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 160, 110));

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortBtnGrp.add(sortByIdBtn);
        sortByIdBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sortByIdBtn.setForeground(new java.awt.Color(255, 255, 255));
        sortByIdBtn.setText("Task ID");
        sortByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByIdBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sortByIdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 38, 98, -1));

        sortBtnGrp.add(sortByDueDateBtn);
        sortByDueDateBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sortByDueDateBtn.setForeground(new java.awt.Color(255, 255, 255));
        sortByDueDateBtn.setText("Due Date");
        sortByDueDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByDueDateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sortByDueDateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 67, 98, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 130, 110));

        jPanel8.setBackground(new java.awt.Color(102, 51, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mark Task As Completed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        completeCheckBox.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        completeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        completeCheckBox.setText("Completed");
        completeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeCheckBoxActionPerformed(evt);
            }
        });
        jPanel8.add(completeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 90, 113, 33));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Task ID");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 40, 60, 30));
        jPanel8.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 42, 60, 30));

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel8.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 108, -1, -1));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 319, 160));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 376, 620));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Description", "Due Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(true);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 800, 260));

        removeBtn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        removeBtn.setText("Remove Task");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 160, 60));

        AddBtn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AddBtn.setText("Add Task");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 160, 60));

        dueDate.setBackground(new java.awt.Color(0, 0, 0));
        dueDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 270, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1224, 723));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        //load data from file. because we need to remove affect for taskList from using sort buttons
        tskListCtrl.getAllTaskListFromFile();   

        if(!"".equals(titleTxt.getText()) && dueDate.getDate() != null){
            
            //convert util date to local Date
            Date utilDate = dueDate.getDate();
            Instant instant = utilDate.toInstant();
            ZoneId zoneId = ZoneId.systemDefault();
            ZonedDateTime zonedDateTime = instant.atZone(zoneId);
            LocalDate localDate = zonedDateTime.toLocalDate();
            
            //generate ID
            tempId = tempId + 1;
            
            //create task object with user values
            Task t = new Task(tempId, titleTxt.getText(), descriptionTxt.getText(), localDate);
            
            //add task to my task List
            tskListCtrl.getTskList().addTask(t);

            //update file
            tskListCtrl.updateFile(tskListCtrl.getTskList());
            
            loadtable();    //refresh table
            
            displaySummary();   //update summary view
            allTaskBtn.setSelected(true);   //select all task radio button
            sortBtnGrp.clearSelection();      //clear sorting selection
            JOptionPane.showMessageDialog(null, "Task Added Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            //clear values
            titleTxt.setText("");
            descriptionTxt.setText("");
            dueDate.setDate(null);    
        }else{
            JOptionPane.showMessageDialog(null, "Please Fill details");
        }   
    }//GEN-LAST:event_AddBtnActionPerformed

    private void completeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completeCheckBoxActionPerformed

    private void allTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTaskBtnActionPerformed
        tskListCtrl.getAllTaskListFromFile();   //load tasks from file
        loadtable();
        sortBtnGrp.clearSelection();     
    }//GEN-LAST:event_allTaskBtnActionPerformed

    private void completedTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedTaskBtnActionPerformed
        tskListCtrl.setTskList(tskListCtrl.getTskList().getCompletedTaskList());
        loadtable();
        sortBtnGrp.clearSelection();     
    }//GEN-LAST:event_completedTaskBtnActionPerformed

    private void sortByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByIdBtnActionPerformed
        tskListCtrl.getTskList().sortById();
        loadtable();
    }//GEN-LAST:event_sortByIdBtnActionPerformed

    private void sortByDueDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByDueDateBtnActionPerformed
        tskListCtrl.getTskList().sortByDate();
        loadtable();
    }//GEN-LAST:event_sortByDueDateBtnActionPerformed

    
    
    
    
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        tskListCtrl.getAllTaskListFromFile();   //load data again from file due to handle the extreme situation(sort button selected situation)  
        try {           //this try for handle invalid number format
            int idToRemove = Integer.parseInt(JOptionPane.showInputDialog("Enter Task ID"));
            Task removedTask = tskListCtrl.getTskList().deleteTask(idToRemove);
            if (removedTask != null) {
                tskListCtrl.updateFile(tskListCtrl.getTskList()); //overwrite file with new task list after remove task
                allTaskBtn.setSelected(true);    //handle all task btn
                sortBtnGrp.clearSelection();    //clear sort btn
                loadtable();    //update table
                displaySummary();   //update summary view
                JOptionPane.showMessageDialog(null, "Task removed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Task not found", "Error", JOptionPane.ERROR_MESSAGE);
            } 
        } catch (NumberFormatException e) {
            
        }  
        
    }//GEN-LAST:event_removeBtnActionPerformed

    
    
    
    
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        tskListCtrl.getAllTaskListFromFile(); //load data from file handle to if sorting select before the update
        try {        //try catch handle invalid number format
            int inputId = Integer.parseInt(idTxt.getText());        //conver string to int
            if (tskListCtrl.getTskList().findTask(inputId) != null) {       //check ther is a task in that ID
                if (completeCheckBox.isSelected()) {
                    tskListCtrl.getTskList().markCompleteTask(inputId);
                    
                    //overwrite file
                    tskListCtrl.updateFile(tskListCtrl.getTskList());     
                    loadtable();    //update table
                    displaySummary();   //update summary view
                    allTaskBtn.setSelected(true);    //handle all task btn
                    sortBtnGrp.clearSelection();    //clear sort btn
                    JOptionPane.showMessageDialog(null, "Mark Task As Completed Task!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    idTxt.setText("");      //clear vaules
                    completeCheckBox.setSelected(false);    //clear vaules
                }else{
                    JOptionPane.showMessageDialog(null, "Mark Task as completed", "Question", JOptionPane.QUESTION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Task not found", "Error", JOptionPane.ERROR_MESSAGE);
                idTxt.setText("");      //clear vaules
                completeCheckBox.setSelected(false);    //clear vaules
            }           
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Enter Task Id", "Warning", JOptionPane.WARNING_MESSAGE);
        }  
        
    }//GEN-LAST:event_saveBtnActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JRadioButton allTaskBtn;
    private swing.CircleProgressBar circleProgressBar1;
    private javax.swing.JCheckBox completeCheckBox;
    private javax.swing.JRadioButton completedTaskBtn;
    private javax.swing.JLabel dateDisplay;
    private javax.swing.JTextArea descriptionTxt;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel noOfAllTasksLabel;
    private javax.swing.JLabel noOfCompleteTasksLabel;
    private javax.swing.JLabel noOfRemainTasksLable;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.ButtonGroup showBtnGrp;
    private javax.swing.ButtonGroup sortBtnGrp;
    private javax.swing.JRadioButton sortByDueDateBtn;
    private javax.swing.JRadioButton sortByIdBtn;
    private javax.swing.JPanel taskShowPannel;
    private javax.swing.JLabel timeDisplay;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
